import { Router } from 'express';
import acceptOrderRoutes from './accept-order.routes';
import approvePayoutRoutes from './approve-payout.routes';
import calculateShippingRoutes from './calculate-shipping.routes';
import checkOrdersRoutes from './check-orders.routes';
import checkTablesRoutes from './check-tables.routes';
import checkoutRoutes from './checkout.routes';
import debugOrdersRoutes from './debug-orders.routes';
import earningsOverviewRoutes from './earnings-overview.routes';
import freezeSellerRoutes from './freeze-seller.routes';
import getAllPayoutsRoutes from './get-all-payouts.routes';
import getMakerOrdersRoutes from './get-maker-orders.routes';
import getOrderNotificationsRoutes from './get-order-notifications.routes';
import getPendingOrdersRoutes from './get-pending-orders.routes';
import getSellersRoutes from './get-sellers.routes';
import getUserOrdersRoutes from './get-user-orders.routes';
import markDeliveredRoutes from './mark-delivered.routes';
import rejectOrderRoutes from './reject-order.routes';
import rejectOrderItemRoutes from './reject-order-item.routes';
import requestPayoutRoutes from './request-payout.routes';
import sellerOrdersRoutes from './seller-orders.routes';
import updateFulfillmentRoutes from './update-fulfillment.routes';
import updateShipmentRoutes from './update-shipment.routes';
import verifyPaymentRoutes from './verify-payment.routes';
import getPendingSubscriptionsRoutes from './get-pending-subscriptions.routes';
import approveSubscriptionRoutes from './approve-subscription.routes';
import rejectSubscriptionRoutes from './reject-subscription.routes';
import getUserSubscriptionsRoutes from './get-user-subscriptions.routes';

const router = Router();

router.use('/accept-order', acceptOrderRoutes);
router.use('/approve-payout', approvePayoutRoutes);
router.use('/calculate-shipping', calculateShippingRoutes);
router.use('/check-orders', checkOrdersRoutes);
router.use('/check-tables', checkTablesRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/debug-orders', debugOrdersRoutes);
router.use('/earnings-overview', earningsOverviewRoutes);
router.use('/freeze-seller', freezeSellerRoutes);
router.use('/get-all-payouts', getAllPayoutsRoutes);
router.use('/get-maker-orders', getMakerOrdersRoutes);
router.use('/get-order-notifications', getOrderNotificationsRoutes);
router.use('/get-pending-orders', getPendingOrdersRoutes);
router.use('/get-sellers', getSellersRoutes);
router.use('/get-user-orders', getUserOrdersRoutes);
router.use('/mark-delivered', markDeliveredRoutes);
router.use('/reject-order', rejectOrderRoutes);
router.use('/reject-order-item', rejectOrderItemRoutes);
router.use('/request-payout', requestPayoutRoutes);
router.use('/seller-orders', sellerOrdersRoutes);
router.use('/update-fulfillment', updateFulfillmentRoutes);
router.use('/update-shipment', updateShipmentRoutes);
router.use('/verify-payment', verifyPaymentRoutes);
router.use('/get-pending-subscriptions', getPendingSubscriptionsRoutes);
router.use('/approve-subscription', approveSubscriptionRoutes);
router.use('/reject-subscription', rejectSubscriptionRoutes);
router.use('/get-user-subscriptions', getUserSubscriptionsRoutes);

export default router;
